// <auto-generated />
namespace TestLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PassWordChange04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PassWordChange04));
        
        string IMigrationMetadata.Id
        {
            get { return "201603251505499_PassWordChange04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
